### ISSUE TITLE
API Setup

### ISSUE THREAD

**Issue by kolawoletech** [Eldow/speeroo#1]
Just wanted to ask how you setup the API on Auth0? Also there was been a changes to the link to one of your css cdn file (bootswatch) and finaally the api link now has a /v2 at the end.
I would like to contribute to this project

**Comment by Eldow** [comment]
After creating a new app on auth0 you will be provided a clientID and organization to paste here: `/src/app/auth/auth.config.ts`
You will also need to add a callback url in the auth0 app settings panel and make sure it's the same in the file located at `src/app/auth/auth.service.ts` on line  16: `redirectUrl: 'https://speeroo.herokuapp.com`

This is the quick and dirty way, the best practice would be to set them in the environment files in the folder  `src/environments` and to import the variables where needed.

If you want to contribute I'd suggest you make a fork as I am not maintaining the codebase for now.

Thanks for the updates on the bootswatch new cdn :), regards

**Comment by kolawoletech** [comment]
I still could not setup the api locally 

Error 

Failed to load https://ferryme.auth0.com/user/ssodata/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 404.
index.js:541 There was an error fetching the SSO data. This could simply mean that there was a problem with the network. But, if a "Origin" error has been logged before this warning, please add "http://localhost:4200" to the "Allowed Origins (CORS)" list in the Auth0 dashboard: https://manage.auth0.com/#/applications/############################/settings
warn @ index.js:541
errorFn @ remote_data.js:71
(anonymous) @ sync.js:88
webpackJsonp.693.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.693.Zone.runTask @ zone.js:188
webpackJsonp.693.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp.693.ZoneDelegate.scheduleTask @ zone.js:407
webpackJsonp.693.Zone.scheduleTask @ zone.js:232
webpackJsonp.693.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
(anonymous) @ sync.js:87
(anonymous) @ index.js:53
updateInDeepMap @ immutable.js:1971
updateInDeepMap @ immutable.js:1980
updateInDeepMap @ immutable.js:1980
Map.updateIn @ immutable.js:1278
updateEntity @ index.js:52
swap @ atom.js:25
swap @ index.js:44
(anonymous) @ sync.js:83
webpackJsonp.693.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.693.Zone.runTask @ zone.js:188
webpackJsonp.693.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp.693.ZoneDelegate.scheduleTask @ zone.js:407
webpackJsonp.693.Zone.scheduleTask @ zone.js:232
webpackJsonp.693.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
(anonymous) @ sync.js:82
(anonymous) @ cache.js:49
execCallbacks @ cache.js:48
(anonymous) @ cache.js:33
(anonymous) @ response-handler.js:64
Request.callback @ client.js:611
Request.crossDomainError @ client.js:628
xhr.onreadystatechange @ client.js:703
wrapFn @ zone.js:1188
webpackJsonp.693.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.693.Zone.runTask @ zone.js:188
webpackJsonp.693.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2969
webpackJsonp.693.ZoneDelegate.scheduleTask @ zone.js:407
webpackJsonp.693.Zone.scheduleTask @ zone.js:232
webpackJsonp.693.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:3001
proto.(anonymous function) @ zone.js:1394
Request._end @ client.js:772
Request.end @ client.js:676
RequestObj.end @ request-builder.js:58
Authentication.getSSOData @ index.js:382
getSSOData @ legacy_api.js:211
getSSOData @ web_api.js:93
(anonymous) @ data.js:17
fetch @ cache.js:31
get @ cache.js:25
fetchSSOData @ data.js:21
syncFn @ remote_data.js:57
(anonymous) @ sync.js:79
process @ sync.js:74
(anonymous) @ index.js:53
updateInDeepMap @ immutable.js:1971
updateInDeepMap @ immutable.js:1980
updateInDeepMap @ immutable.js:1980
Map.updateIn @ immutable.js:1278
updateEntity @ index.js:52
swap @ atom.js:25
swap @ index.js:44
(anonymous) @ sync.js:117
webpackJsonp.693.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.693.Zone.runTask @ zone.js:188
webpackJsonp.693.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp.693.ZoneDelegate.scheduleTask @ zone.js:407
webpackJsonp.693.Zone.scheduleTask @ zone.js:232
webpackJsonp.693.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
(anonymous) @ sync.js:116
(anonymous) @ index.js:31
(anonymous) @ atom.js:54
_change @ atom.js:53
swap @ atom.js:25
swap @ index.js:44
(anonymous) @ sync.js:117
webpackJsonp.693.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.693.Zone.runTask @ zone.js:188
webpackJsonp.693.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp.693.ZoneDelegate.scheduleTask @ zone.js:407
webpackJsonp.693.Zone.scheduleTask @ zone.js:232
webpackJsonp.693.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
(anonymous) @ sync.js:116
(anonymous) @ index.js:31
(anonymous) @ atom.js:54
_change @ atom.js:53
swap @ atom.js:25
swap @ index.js:44
(anonymous) @ sync.js:83
webpackJsonp.693.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.693.Zone.runTask @ zone.js:188
webpackJsonp.693.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp.693.ZoneDelegate.scheduleTask @ zone.js:407
webpackJsonp.693.Zone.scheduleTask @ zone.js:232
webpackJsonp.693.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
(anonymous) @ sync.js:82
(anonymous) @ cdn_utils.js:36
webpackJsonp.693.ZoneDelegate.invokeTask @ zone.js:421
webpackJsonp.693.Zone.runTask @ zone.js:188
webpackJsonp.693.ZoneTask.invokeTask @ zone.js:496
ZoneTask.invoke @ zone.js:485
timer @ zone.js:2054
setTimeout (async)
scheduleTask @ zone.js:2075
webpackJsonp.693.ZoneDelegate.scheduleTask @ zone.js:407
webpackJsonp.693.Zone.scheduleTask @ zone.js:232
webpackJsonp.693.Zone.scheduleMacroTask @ zone.js:255
scheduleMacroTaskWithCurrentZone @ zone.js:1114
(anonymous) @ zone.js:2090
proto.(anonymous function) @ zone.js:1394
(anonymous) @ cdn_utils.js:35
global.Auth0.(anonymous function) @ cdn_utils.js:33
(anonymous) @ 
 6lT5KjBicBIedjo###########aVr8OA.js?t1526419738030:1

**Comment by Eldow** [comment]
Did you follow the link and added http://localhost:4200 as an authorized origin in your auth0 dashboard ?

**Comment by kolawoletech** [comment]
yes I did

**Comment by Eldow** [comment]
I just tried cloning the app and then modified the redirectUrl and everything worked.
I looked into my auth0 configuration and nothing unusual there. only an app with the `http://localhost:4200` url allowed. Try adding `https://localhost:4200/` aswell and turning off the OIDC conformant switch in advanced settings.

Make sure the app setting is set on Single Page Application

I made a custom rule in the auth0 dashboard to add a first sign up field inside the json sent back by the sso but this shouldn't be the cause of the error, you'll need it though.

```
function (user, context, callback) {
  user.app_metadata = user.app_metadata || {};
  // short-circuit if the user signed up already
  if (user.app_metadata.signed_up) {
    user.signed_up = false;
    return callback(null, user, context);
  }
  // first time login/signup
  user.app_metadata.signed_up = true;
  user.signed_up = user.app_metadata.signed_up;
    auth0.users.updateAppMetadata(user.user_id, user.app_metadata)
    .then(function(){
      callback(null, user, context);
    })
    .catch(function(err){
      callback(err);
    });
}
```
